import { create } from 'zustand';

type Language = 'uz' | 'ru' | 'en';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  uz: {
    discover: 'Avtomobillarni toping',
    browse: 'Bizning premium avtomobillar kolleksiyasini ko\'ring.',
    searchPlaceholder: 'Brend yoki model bo\'yicha qidirish...',
    filters: 'Filtrlar',
    buyNow: 'Sotib olish',
    login: 'Kirish',
    register: 'Ro\'yxatdan o\'tish',
    logout: 'Chiqish',
    adminDashboard: 'Admin boshqaruv paneli',
    mileage: 'Masofasi',
    condition: 'Holati',
    year: 'Yili',
    cancel: 'Bekor qilish',
    confirmOrder: 'Buyurtmani tasdiqlash',
    orderSuccess: 'Buyurtma muvaffaqiyatli qabul qilindi!',
    noVehicles: 'Sizning qidiruvingiz bo\'yicha hech narsa topilmadi.',
    welcomeBack: 'Xush kelibsiz',
    signInToContinue: 'Davom etish uchun hisobingizga kiring',
    emailLabel: 'Elektron pochta',
    passwordLabel: 'Parol',
    forgotPassword: 'Parolni unutdingizmi?',
    signInButton: 'Kirish',
    createAccount: 'Hisob yaratish',
    joinToday: 'Bugun Drive.net ga qo\'shiling',
    fullName: 'To\'liq ism',
    selectPlan: 'Bo\'lib to\'lash rejasini tanlang',
    payFull: 'To\'liq to\'lash',
    noInterest: 'Foizsiz (0%)',
    months: 'oy',
    interest: 'Foiz',
    summary: 'Jami ma\'lumotlar',
    basePrice: 'Asosiy narx',
    total: 'Jami',
    monthlyPayment: 'Oylik to\'lov',
    pending: 'Kutilmoqda',
    confirmed: 'Tasdiqlangan',
    delivered: 'Yetkazilgan',
    orderId: 'Buyurtma ID',
    customer: 'Mijoz',
    vehicle: 'Avtomobil',
    date: 'Sana',
    amount: 'Summa',
    status: 'Holati',
  },
  ru: {
    discover: 'Найдите автомобили',
    browse: 'Ознакомьтесь с нашей коллекцией премиальных авто.',
    searchPlaceholder: 'Поиск по марке или модели...',
    filters: 'Фильтры',
    buyNow: 'Купить сейчас',
    login: 'Войти',
    register: 'Регистрация',
    logout: 'Выйти',
    adminDashboard: 'Панель администратора',
    mileage: 'Пробег',
    condition: 'Состояние',
    year: 'Год',
    cancel: 'Отмена',
    confirmOrder: 'Подтвердить заказ',
    orderSuccess: 'Заказ успешно оформлен!',
    noVehicles: 'По вашему запросу ничего не найдено.',
    welcomeBack: 'С возвращением',
    signInToContinue: 'Войдите в свой аккаунт, чтобы продолжить',
    emailLabel: 'Электронная почта',
    passwordLabel: 'Пароль',
    forgotPassword: 'Забыли пароль?',
    signInButton: 'Войти',
    createAccount: 'Создать аккаунт',
    joinToday: 'Присоединяйтесь к Drive.net сегодня',
    fullName: 'Полное имя',
    selectPlan: 'Выберите план рассрочки',
    payFull: 'Оплатить полностью',
    noInterest: 'Без процентов (0%)',
    months: 'мес.',
    interest: 'Процент',
    summary: 'Итоговая информация',
    basePrice: 'Базовая цена',
    total: 'Итого',
    monthlyPayment: 'Ежемесячный платеж',
    pending: 'В ожидании',
    confirmed: 'Подтвержден',
    delivered: 'Доставлен',
    orderId: 'ID Заказа',
    customer: 'Клиент',
    vehicle: 'Автомобиль',
    date: 'Дата',
    amount: 'Сумма',
    status: 'Статус',
  },
  en: {
    discover: 'Discover Vehicles',
    browse: 'Browse our exclusive collection of premium cars.',
    searchPlaceholder: 'Search by brand or model...',
    filters: 'Filters',
    buyNow: 'Buy Now',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    adminDashboard: 'Admin Dashboard',
    mileage: 'Mileage',
    condition: 'Condition',
    year: 'Year',
    cancel: 'Cancel',
    confirmOrder: 'Confirm Order',
    orderSuccess: 'Order placed successfully!',
    noVehicles: 'No vehicles found matching your criteria.',
    welcomeBack: 'Welcome Back',
    signInToContinue: 'Sign in to your account to continue',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    forgotPassword: 'Forgot password?',
    signInButton: 'Sign In',
    createAccount: 'Create Account',
    joinToday: 'Join Drive.net today',
    fullName: 'Full Name',
    selectPlan: 'Select Installment Plan',
    payFull: 'Pay in Full',
    noInterest: 'No extra interest',
    months: 'Months',
    interest: 'Interest',
    summary: 'Summary',
    basePrice: 'Base Price',
    total: 'Total',
    monthlyPayment: 'Monthly Payment',
    pending: 'Pending',
    confirmed: 'Confirmed',
    delivered: 'Delivered',
    orderId: 'Order ID',
    customer: 'Customer',
    vehicle: 'Vehicle',
    date: 'Date',
    amount: 'Amount',
    status: 'Status',
  },
};

export const useLanguageStore = create<LanguageState>((set, get) => ({
  language: 'uz',
  setLanguage: (lang) => set({ language: lang }),
  t: (key) => translations[get().language][key] || key,
}));
